let ids = [
    {name: "lotion", h:"90", w:"95"},
    {name: "workUniform",h:"75",w:"60"},
    {name: "pouchOfGalleons",h:"80",w:"85"},
    {name: "bankNote",h:"80",w:"85"},
    {name: "car",h:"35",w:"70"},
    {name: "pudding",h:"70",w:"95"},
    {name: "vaultKey",h:"50",w:"75"},
    {name: "plasticMouse",h:"62",w:"75"},
    {name: "bludger",h:"50",w:"50"},
    {name: "phone",h:"60",w:"80"},
    {name: "blastEndedSkrewt",h:"65",w:"95"},
    {name: "cookingPot",h:"70",w:"75"},
    {name: "norbert",h:"45",w:"80"},
    {name: "beadedShawls",h:"60",w:"65"},
    {name: "goblinHelmet",h:"65",w:"125"},
    {name: "copperMouse",h:"65",w:"75"},
    {name: "buckBeak",h:"65",w:"105"},
    {name: "crystalBall",h:"75",w:"80"},
    {name: "computer",h:"65",w:"70"},
    {name: "prefectBadge",h:"60",w:"55"},
    {name: "sock",h:"75",w:"80"},
    {name: "lightningStruckTower",h:"75",w:"60"},
    {name: "wolfsbanePotion",h:"85",w:"65"},
    {name: "gingerNewt",h:"70",w:"75"},
    {name: "ukrainianIronbelly",h:"35",w:"83"},
    {name: "ironMouse",h:"65",w:"75"},
    {name: "fluffy",h:"65",w:"70"},
    {name: "wolfPatronus",h:"55",w:"85"},
    {name: "spectacles",h:"70",w:"75"},
    {name: "lacewingFlys",h:"70",w:"80"},
    {name: "freeElf",h:"70",w:"55"},
    {name: "theGrim",h:"60",w:"73"},
    {name: "headGirlBadge",h:"85",w:"90"},
    {name: "potionStoreroom",h:"65",w:"55"},
    {name: "titaniumMouse",h:"65",w:"75"},
    {name: "spiderSpray",h:"65",w:"70"},
    {name: "arragog",h:"70",w:"85"},
    {name: "maraudersMap",h:"50",w:"75"},
    {name: "felixFelicis",h:"75",w:"75"},
    {name: "chocolateFrogCard",h:"60",w:"65"},
    {name: "harrysProphecy",h:"64",w:"85"},
    {name: "polyjuicePotion",h:"95",w:"100"},
    {name: "wizardsChessSet",h:"80",w:"85"},
    {name: "lovePotion",h:"60",w:"65"},
    {name: "talesOfBeedleTheBard",h:"90",w:"95"},
    {name: "magicalMouse",h:"60",w:"70"},
    {name: "moon",h:"60",w:"110"},
    {name: "halfMoonGlasses",h:"45",w:"80"},
    {name: "halfBloodPrincesBook",h:"65",w:"50"},
    {name: "magicallyEnlargedBag",h:"80",w:"65"},
    {name: "orderOfMerlin1stClass",h:"70",w:"95"},
    {name: "tabbyCat",h:"65",w:"90"},
    {name: "pheonixTears",h:"75",w:"85"},
    {name: "scabbers",h:"70",w:"75"},
    {name: "pensive",h:"65",w:"70"},
    {name: "theGobletOfFire",h:"50",w:"115"},
    {name: "doePatronus",h:"85",w:"70"},
    {name: "tomRiddlesDiary",h:"75",w:"80"},
    {name: "crookshanks",h:"90",w:"95"},
    {name: "resurrectionStone",h:"90",w:"150"},
    {name: "gauntFamilyRing",h:"65",w:"65"},
    {name: "deluminator",h:"75",w:"90"},
    {name: "fawkesThePheonix",h:"60",w:"65"},
    {name: "slitherensLocket",h:"75",w:"80"},
    {name: "timeTurner",h:"75",w:"80"},
    {name: "elderWand",h:"60",w:"65"},
    {name: "swordOfGryffindor",h:"60",w:"65"},
    {name: "ravenclawsDiadem",h:"75",w:"80"},
    {name: "cloakOfInvisibility",h:"65",w:"45"},
    {name: "hufflepuffsCup",h:"60",w:"65"},
    {name: "nagini",h:"50",w:"70"},
    {name: "harryPotter",h:"70",w:"58"}
];

function upgradeImages(){
    ids.forEach(function(ids){
        let upperCaseId = ids.name[0].toUpperCase() +  ids.name.substring(1)
        document.writeln('<div class="Upgrades"  id="' + ids.name + '" onclick="buyUpgrade(this)" onmousemove="upgradeInfoUpdate(this)" onmouseleave="upgradeInfoRemove()" style="display: none">');
        document.writeln('  <img src="Pictures/Upgrades/' + upperCaseId + '.png" height="' + ids.h + '" width ="' + ids.w + '" alt="">');
        document.writeln('</div>');
    });
}

upgradeImages();